KVM and Kickstart

diff --git a/environment b/environment
--- a/environment
+++ b/environment
@@ -1,15 +1,21 @@
 #! /bin/bash
 
+ip_1=`echo ${MY_IP} | awk -F. '{print $1}'`
+ip_2=`echo ${MY_IP} | awk -F. '{print $2}'`
+ip_3=`echo ${MY_IP} | awk -F. '{print $3}'`
 systemctl stop firewalld
 systemctl disable firewalld
-sed 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
+sed 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config &> /dev/null
 setenforce 0
+[ $? -eq 0 ] && echo "firewalld and selinux is OK! "
+echo""
 cat > /etc/sysconfig/network-scripts/ifcfg-em1 << EOF
 DEVICE=em1
 TYPE=Ethernet
 ONBOOT=yes
 BRIDGE=br0
 EOF
+sed -i "s,ONBOOT=yes,ONBOOT=no,g" /etc/sysconfig/network-scripts/ifcfg-em2
 cat > /etc/sysconfig/network-scripts/ifcfg-br0 << EOF
 DEVICE=br0
 TYPE=Bridge
@@ -17,9 +23,11 @@ ONBOOT=yes
 BOOTPROTO=static
 IPADDR=${MY_IP}
 NETMASK=255.255.255.0
-GATEWAY=192.168.1.1
+GATEWAY=${ip_1}.${ip_2}.${ip_3}.1
 EOF
 systemctl restart network
+[ $? -eq 0 ] && echo "network is OK! "
+echo ""
 ISO=`find /home/ -name *.iso | head -n 1 | awk -F/ '{print $3}'`
 PKGS=(
 net-tools
@@ -30,11 +38,12 @@ libvirt
 virt-install
 virt-manager
 httpd
+dhcp
 )
-mv /home/${ISO} /home/centos7.iso
-mount /home/centos7.iso /mnt
-mkdir /etc/yum.repos.d/bak
-mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/bak
+mv -f /home/${ISO} /home/centos7.iso &> /dev/null
+mount /home/centos7.iso /mnt &> /dev/null
+mkdir /etc/yum.repos.d/bak &> /dev/null
+mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/bak &> /dev/null
 cat > /etc/yum.repos.d/qyy.repo << EOF
 [qyy]
 name=qyy
@@ -42,14 +51,16 @@ baseurl=file:///mnt/
 gpgcheck=0
 enabled=1
 EOF
-yum clean all && yum makecache
-yum install ${PKGS[*]} -y
-systemctl start libvirtd httpd
-[ $? -ne 0 ] && exit
-systemctl enable libvirtd httpd
-mkdir /var/www/html/repos
-umount /mnt
-mount /home/centos7.iso /var/www/html/repos
+yum clean all  &> /dev/null && yum makecache &> /dev/null
+yum install ${PKGS[*]} -y &> /dev/null
+[ $? -eq 0 ] && echo "PKGS is OK! "
+echo ""
+systemctl start libvirtd httpd &> /dev/null
+[ $? -ne 0 ] && exit && echo "Service Error!! "
+systemctl enable libvirtd httpd &> /dev/null
+mkdir /var/www/html/repos &> /dev/null
+umount /mnt &> /dev/null
+mount /home/centos7.iso /var/www/html/repos &> /dev/null
 cat > /etc/yum.repos.d/qyy.repo << EOF
 [qyy]
 name=qyy
@@ -57,7 +68,9 @@ baseurl=http://${MY_IP}/repos
 gpgcheck=0
 enabled=1
 EOF
-yum clean all && yum makecache
+yum clean all &> /dev/null && yum makecache &> /dev/null
+[ $? -eq 0 ] && echo "Bridge and repos is OK! "
+echo ""
 cat >> /etc/rc.d/rc.local << EOF
 mount /home/centos7.iso /var/www/html/repos
 EOF
@@ -66,8 +79,10 @@ TimeZone=`timedatectl | grep "Time zone" | awk '{ print $3 }' | awk -F/ '{ print
 if [[ ${TimeZone} != Shanghai ]]; then
 	timedatectl set-timezone Asia/Shanghai
 	echo "TimeZone is OK!"
+	echo ""
 else
 	echo "TimeZone is Shanghai"
+	echo ""
 fi
 #Crontab Script
 mkdir /home/script &> /dev/null
@@ -98,6 +113,9 @@ if [[ $? -eq 0 ]]; then
 	echo "55 23 * * * source /home/script/vm_shutdown.sh" >> /var/spool/cron/root
 	echo "0 0 * * * source /home/script/poweroff.sh" >> /var/spool/cron/root
 	echo "crond is OK!"
+	echo ""
+	echo "Environment Complete! "
+	echo ""
 else
 	echo "E: crond not running"
 fi
diff --git a/installation b/installation
--- a/installation
+++ b/installation
@@ -1,8 +1,11 @@
 #!/bin/bash
 
 single=1
-DISK_SIZE=50
+DISK_SIZE=100
 MY_IP=`ifconfig br0 | grep -w inet | awk '{print $2}'`
+ip_1=`echo ${MY_IP} | awk -F. '{print $1}'`
+ip_2=`echo ${MY_IP} | awk -F. '{print $2}'`
+ip_3=`echo ${MY_IP} | awk -F. '{print $3}'`
 PASSWD_NEW=`openssl passwd ${PASSWD}`
 cat > /var/www/html/ks.cfg << EOF
 install		
@@ -25,30 +28,7 @@ bootloader --append="quiet crashkernel=auto" --location=mbr
 clearpart --all --initlabel
 part /boot --fstype="ext4" --size=1024
 part swap --fstype="swap" --size=4096
-part / --fstype="ext4" --grow --size=46080
-
-#%post
-#rm -f /etc/yum.repos.d/*
-#cat >>/etc/yum.repos.d/base.repo<<eof
-#[base]
-#name=sohu
-#baseurl=http://mirrors.sohu.com/centos/7/os/x86_64/
-#gpgcheck=0
-#enable=1
-#[epel]
-#name=epel
-#baseurl=http://mirrors.aliyun.com/epel/7Server/x86_64/
-#enable=1
-#gpgcheck=0
-#eof
-#sed -i "s/rhgb //" /boot/grub2/grub.cfg
-#sed -i "s/ONBOOT.*$/ONBOOT=yes/" /etc/sysconfig/network-scripts/ifcfg-eth0
-#sed -i "/UUID/d" /etc/sysconfig/network-scripts/ifcfg-eth0
-#echo "DNS1=114.114.114.114" >> /etc/sysconfig/network-scripts/ifcfg-eth0
-#echo "UseDNS no" >> /etc/ssh/sshd_config
-#sed -i "s/^SELINUX=.*$/SELINUX=disabled/" /etc/sysconfig/selinux
-#systemctl disable firewalld
-#%end
+part / --fstype="ext4" --grow --size=96256
 
 %packages
 @^minimal
@@ -57,6 +37,18 @@ chrony
 
 %end
 EOF
+version=`rpm -qa | grep dhcp-4 | awk -F\- '{print $2}'`
+/bin/cp -f /usr/share/doc/dhcp-${version}/dhcpd.conf.example /etc/dhcp/dhcpd.conf &> /dev/null
+cat >> /etc/dhcp/dhcpd.conf << EOF
+subnet ${ip_1}.${ip_2}.${ip_3}.0 netmask 255.255.255.0 {
+    option routers ${ip_1}.${ip_2}.${ip_3}.1;
+    option subnet-mask 255.255.255.0;
+    range dynamic-bootp ${ip_1}.${ip_2}.${ip_3}.10 ${ip_1}.${ip_2}.${ip_3}.15;
+}
+EOF
+systemctl restart dhcpd &> /dev/null
+[ $? -ne 0 ] && exit && echo "DHCP Service Error!! "
+sleep 3
 virt-install \
 --name server_init \
 --memory ${MEM} \
@@ -68,16 +60,21 @@ virt-install \
 --initrd-inject /var/www/html/ks.cfg \
 --noautoconsole \
 -x "ks=http://${MY_IP}/ks.cfg console=tty0 console=ttyS0,115200n8"
+echo "--------------------------"
+echo "Installation, please wait..."
 while [ ${single} -eq 1 ]
 do
 	virsh list > /home/vm1.txt
 	cat /home/vm1.txt | grep -v "^$" | awk 'NR>2{print $2}' > /home/vm2.txt
 	if [ -s /home/vm2.txt ]; then
 		single=1
+		sleep 10
 	else
+		echo ""
+		echo "Installation Complete! "
 		single=0
 		rm -rf /home/vm1.txt /home/vm2.txt
 	fi
 done
 virsh dumpxml server_init > /home/server.xml
-#virsh destroy server_init 
+virsh undefine server_init &> /dev/null
